-- generated by hosc1 from examples/sc/01_loop.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec f=(\p1-> (\r1-> case  p1  of { Z  -> (d r1); S y1 -> ((f y1) (S r1)); })) in ((f x) y))
