-- generated by hosc1 from examples/eq/churchMult2.hs

data Nat  = Z  | S Nat;

(letrec
  f=(\p1->
    (\r1->
      case  p1  of {
        Z  -> Z;
        S z1 -> (letrec g=(\s1-> case  s1  of { Z  -> ((f z1) r1); S t -> (S (g t)); }) in (g r1));
      }))
in
  ((f x) y))
