-- generated by hosc1 from examples/sc/eqnum.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;
data Pair  = P Number Number;

(letrec
  f=(\z14->
    (\u14->
      case  z14  of {
        Z  ->
          (letrec
            g=(\v14->
              (\w14->
                case  v14  of {
                  Z  ->
                    (letrec
                      h=(\p14->
                        (\r14->
                          case  p14  of {
                            Z  -> case  r14  of { Z  -> True; S r11 -> False; };
                            S v6 -> case  r14  of { Z  -> False; S y7 -> ((h v6) y7); };
                          }))
                    in
                      ((h w14) x));
                  S t9 -> case  w14  of { Z  -> case  t9  of { Z  -> False; S y11 -> False; }; S r -> ((g t9) r); };
                }))
          in
            ((g u14) y));
        S v9 ->
          case  u14  of {
            Z  ->
              (letrec
                f1=(\s14->
                  (\t14->
                    case  s14  of {
                      Z  ->
                        (letrec
                          g1=(\x15->
                            (\y15->
                              case  x15  of {
                                Z  -> False;
                                S x3 ->
                                  case  y15  of {
                                    Z  -> case  x3  of { Z  -> True; S u8 -> False; };
                                    S y10 -> ((g1 x3) y10);
                                  };
                              }))
                        in
                          ((g1 t14) y));
                      S u7 -> case  t14  of { Z  -> False; S v7 -> ((f1 u7) v7); };
                    }))
              in
                ((f1 v9) x));
            S w11 -> ((f v9) w11);
          };
      }))
in
  ((f x) y))
