-- generated by hosc1 from examples/sc/eqnumxx.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;
data Pair  = P Number Number;

(letrec f=(\w1-> case  w1  of { Z  -> True; S t -> (f t); }) in (f x))
