-- generated by hosc1 from examples/sc/evenSS.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec
  f=(\s2->
    (\t2->
      case  s2  of {
        Z  ->
          (letrec g=(\x3-> case  x3  of { Z  -> True; S w2 -> case  w2  of { Z  -> False; S v1 -> (g v1); }; })
          in
            (g t2));
        S y -> ((f y) (S (S t2)));
      }))
in
  ((f n) Z))
