-- generated by hosc1 from examples/sc/even2.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec
  h=(\z2->
    (\u2->
      case  z2  of {
        S x1 -> ((h x1) (S (S u2)));
        Z  ->
          (letrec f1=(\v2-> case  v2  of { Z  -> True; S r -> case  r  of { Z  -> False; S y -> (f1 y); }; })
          in
            (f1 u2));
      }))
in
  ((h t) Z))
