-- generated by hosc1 from examples/sc/even.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec
  f=(\r2->
    (\s2->
      case  r2  of {
        Z  ->
          (letrec g=(\t2-> case  t2  of { S p1 -> case  p1  of { S x -> (g x); Z  -> False; }; Z  -> True; })
          in
            (g s2));
        S u1 -> ((f u1) (S (S s2)));
      }))
in
  ((f n) Z))
