-- generated by hosc1 from examples/sc/exp.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec g=(\w1-> (\p1-> case  w1  of { Z  -> (d (S p1)); S y -> ((g y) (S p1)); })) in ((g x) Z))
