-- generated by hosc1 from examples/sc/fib.hs

data Nat  = Z  | S Nat;

(letrec f=(\y1-> case  y1  of { Z  -> (S Z); S w -> case  w  of { Z  -> (S Z); S v -> ((add (f (S v))) (f v)); }; })
in
  (f n))
