-- generated by hosc1 from examples/sc/filter.hs

data List a = Nil  | Cons a (List a);
data Boolean  = True  | False ;

(letrec
  g=(\u4->
    (letrec
      h=(\v4->
        case  v4  of {
          Nil  -> Nil;
          Cons w1 x4 -> case  (p (f w1))  of { True  -> (Cons (f w1) (g x4)); False  -> (h x4); };
        })
    in
      (h u4)))
in
  (g xs))
