-- generated by hosc1 from examples/sc/join2.hs

data List a = Nil  | Cons a (List a);

(letrec
  g=(\p12->
    case  p12  of {
      Nil  -> Nil;
      Cons s11 y10 ->
        (letrec
          h=(\r12->
            case  r12  of {
              Nil  -> (g y10);
              Cons w3 w11 ->
                (letrec f1=(\s12-> case  s12  of { Nil  -> (h w11); Cons v3 w1 -> (Cons (f v3) (f1 w1)); }) in (f1 w3));
            })
        in
          (h s11));
    })
in
  (g xs))
