-- generated by hosc1 from examples/sc/leq_add.hs

data N  = Z  | S N;
data B  = True  | False ;

case  x  of {
  Z  -> True;
  S w2 ->
    (letrec
      f=(\w4->
        (\p4->
          case  w4  of {
            Z  ->
              (letrec
                g=(\r4->
                  (\s4->
                    case  r4  of { Z  -> True; S s1 -> case  s4  of { Z  -> False; S r3 -> ((g s1) r3); }; }))
              in
                ((g p4) w2));
            S v2 -> case  p4  of { Z  -> True; S z4 -> ((f v2) z4); };
          }))
    in
      ((f y) w2));
}
