-- generated by hosc1 from examples/sc/letrec_rev.hs

data List a = Nil  | Cons a (List a);

(letrec
  g=(\v2->
    case  v2  of {
      Nil  -> Nil;
      Cons y1 v1 ->
        (letrec h=(\w2-> case  w2  of { Cons w x2 -> (Cons w (h x2)); Nil  -> (Cons y1 Nil); }) in (h (g v1)));
    })
in
  (g zs))
