-- generated by hosc1 from examples/sc/letrec.hs

data List a = Nil  | Cons a (List a);

(letrec
  g=(\p2->
    case  p2  of {
      Nil  -> (letrec h=(\r2-> case  r2  of { Nil  -> z; Cons x2 r -> (Cons x2 (h r)); }) in (h y));
      Cons z1 u2 -> (Cons z1 (g u2));
    })
in
  (g x))
