-- generated by hosc1 from examples/mc/ltl1.hs

data Bool  = True  | False ;
data State  = S Bool Bool;
data List a = Cons a (List a);

(letrec
  f=(\v3->
    case 
    case  (qq v3)  of {
      True  -> case  (pp v3)  of { True  -> (f case  v3  of { Cons t2 v2 -> v2; }); False  -> False; };
      False  -> False;
    }
     of {
      False  -> True;
      True  -> False;
    })
in
  (f states))
