-- generated by hosc1 from examples/sc/min.hs

data List a = Nil  | Cons a (List a);
data B  = True  | False ;
data N  = Z  | S N;

case 
(letrec
  f=(\u10->
    case  u10  of {
      Nil  -> Nil;
      Cons w r1 ->
        (letrec
          g=(\v10->
            case  v10  of {
              Cons y8 r6 -> case  ((lessOrEq w) y8)  of { False  -> (Cons y8 (g r6)); True  -> (Cons w (Cons y8 r6)); };
              Nil  -> (Cons w Nil);
            })
        in
          (g (f r1)));
    })
in
  (f w43))
 of {
  Cons x4 p6 ->
    case  ((lessOrEq w42) x4)  of {
      False  -> case  ((lessOrEq x) x4)  of { False  -> x4; True  -> x; };
      True  -> case  ((lessOrEq x) w42)  of { False  -> w42; True  -> x; };
    };
  Nil  -> case  ((lessOrEq x) w42)  of { False  -> w42; True  -> x; };
}
