-- generated by hosc1 from examples/sc/rev.hs

data List a = Nil  | Cons a (List a);

(letrec
  f=(\v2->
    case  v2  of {
      Nil  -> Nil;
      Cons s1 x1 ->
        (letrec g=(\w2-> case  w2  of { Cons v y2 -> (Cons v (g y2)); Nil  -> (Cons s1 Nil); }) in (g (f x1)));
    })
in
  (f xs))
