-- generated by hosc1 from examples/sc/synapse2.hs

data Action  = RM  | WH2 ;
data Number  = Z  | S Number;
data State  = State Number Number Number | Stop ;
data Boolean  = True  | False ;
data List a = Nil  | Cons a (List a);

case  y  of {
  Nil  -> True;
  Cons p16 v36 ->
    (letrec
      g=(\z48->
        (\u48->
          (\v48->
            (\w48->
              case  w48  of {
                Nil  ->
                  case  z48  of {
                    RM  ->
                      case  u48  of { State z r10 u4 -> case  z  of { S x1 -> True; Z  -> True; }; Stop  -> True; };
                    WH2  ->
                      case  v48  of {
                        State t20 p s8 ->
                          case  t20  of {
                            S u5 -> case  s8  of { S w30 -> True; Z  -> True; };
                            Z  -> case  s8  of { S v17 -> True; Z  -> True; };
                          };
                        Stop  -> True;
                      };
                  };
                Cons y42 w9 ->
                  ((((g y42)
                        case  z48  of {
                          RM  ->
                            case  u48  of {
                              State p37 x32 v46 ->
                                case  p37  of {
                                  S z33 ->
                                    (State
                                      (letrec
                                        h=(\p48->
                                          (\r48->
                                            case  p48  of { Z  -> r48; S y17 -> (S ((h r48) y17)); }))
                                      in
                                        ((h z33) x32))
                                      Z
                                      (S v46));
                                  Z  -> Stop;
                                };
                              Stop  -> Stop;
                            };
                          WH2  ->
                            case  v48  of {
                              State v19 v34 u43 ->
                                case  v19  of {
                                  S z43 ->
                                    case  u43  of {
                                      S x11 ->
                                        (State
                                          (S
                                            (letrec
                                              f1=(\s48->
                                                (\t48->
                                                  (\x49->
                                                    case  s48  of {
                                                      Z  ->
                                                        (letrec
                                                          g1=(\y49->
                                                            (\z49->
                                                              case  y49  of {
                                                                Z  -> z49;
                                                                S p23 -> (S ((g1 z49) p23));
                                                              }))
                                                        in
                                                          ((g1 t48) x49));
                                                      S y2 ->
                                                        (S
                                                          case  t48  of {
                                                            Z  ->
                                                              (letrec
                                                                h1=(\u49->
                                                                  (\v49->
                                                                    case  v49  of {
                                                                      Z  -> u49;
                                                                      S t33 -> (S ((h1 t33) u49));
                                                                    }))
                                                              in
                                                                ((h1 y2) x49));
                                                            S r24 -> (S (((f1 y2) x49) r24));
                                                          });
                                                    })))
                                            in
                                              (((f1 x11) v34) z43)))
                                          (S Z)
                                          Z);
                                      Z  ->
                                        (State
                                          (S
                                            (letrec
                                              f2=(\w49->
                                                (\p49->
                                                  case  w49  of { Z  -> p49; S t36 -> (S ((f2 p49) t36)); }))
                                            in
                                              ((f2 v34) z43)))
                                          (S Z)
                                          Z);
                                    };
                                  Z  ->
                                    case  u43  of {
                                      S t24 ->
                                        (State
                                          (letrec
                                            g2=(\r49->
                                              (\s49->
                                                case  s49  of { Z  -> r49; S p4 -> (S ((g2 p4) r49)); }))
                                          in
                                            ((g2 t24) v34))
                                          (S Z)
                                          Z);
                                      Z  -> Stop;
                                    };
                                };
                              Stop  -> Stop;
                            };
                        })
                      case  z48  of {
                        RM  ->
                          case  u48  of {
                            State u7 w24 r43 ->
                              case  u7  of {
                                S w14 ->
                                  (State
                                    (letrec h2=(\t49-> (\x50-> case  t49  of { Z  -> x50; S y1 -> (S ((h2 x50) y1)); }))
                                    in
                                      ((h2 w14) w24))
                                    Z
                                    (S r43));
                                Z  -> Stop;
                              };
                            Stop  -> Stop;
                          };
                        WH2  ->
                          case  v48  of {
                            State w2 x13 v29 ->
                              case  w2  of {
                                S z38 ->
                                  case  v29  of {
                                    S u37 ->
                                      (State
                                        (S
                                          (letrec
                                            f3=(\y50->
                                              (\z50->
                                                (\u50->
                                                  case  y50  of {
                                                    Z  ->
                                                      (letrec
                                                        g3=(\v50->
                                                          (\w50->
                                                            case  v50  of { Z  -> w50; S z11 -> (S ((g3 w50) z11)); }))
                                                      in
                                                        ((g3 z50) u50));
                                                    S w33 ->
                                                      (S
                                                        case  z50  of {
                                                          Z  ->
                                                            (letrec
                                                              h3=(\p50->
                                                                (\r50->
                                                                  case  r50  of {
                                                                    Z  -> p50;
                                                                    S v47 -> (S ((h3 v47) p50));
                                                                  }))
                                                            in
                                                              ((h3 w33) u50));
                                                          S z46 -> (S (((f3 w33) u50) z46));
                                                        });
                                                  })))
                                          in
                                            (((f3 u37) x13) z38)))
                                        (S Z)
                                        Z);
                                    Z  ->
                                      (State
                                        (S
                                          (letrec
                                            f4=(\s50->
                                              (\t50->
                                                case  s50  of { Z  -> t50; S y8 -> (S ((f4 t50) y8)); }))
                                          in
                                            ((f4 x13) z38)))
                                        (S Z)
                                        Z);
                                  };
                                Z  ->
                                  case  v29  of {
                                    S t26 ->
                                      (State
                                        (letrec
                                          g4=(\x51->
                                            (\y51->
                                              case  y51  of { Z  -> x51; S u2 -> (S ((g4 u2) x51)); }))
                                        in
                                          ((g4 t26) x13))
                                        (S Z)
                                        Z);
                                    Z  -> Stop;
                                  };
                              };
                            Stop  -> Stop;
                          };
                      })
                    w9);
              }))))
    in
      ((((g p16) (State (S x) Z Z)) (State (S x) Z Z)) v36));
}
