-- generated by hosc1 from examples/sc/synapse.hs

data Action  = RM  | WH ;
data Number  = Z  | S Number;
data State  = State Number Number Number | Stop ;
data Boolean  = True  | False ;
data List a = Nil  | Cons a (List a);

case  y  of {
  Nil  -> True;
  Cons t8 u2 ->
    (letrec
      f=(\w30->
        (\p30->
          (\r30->
            case  r30  of {
              Nil  ->
                case  w30  of {
                  Stop  -> True;
                  State y11 w10 v21 ->
                    case  p30  of {
                      RM  -> case  y11  of { Z  -> True; S t25 -> True; };
                      WH  ->
                        case  y11  of {
                          Z  -> case  v21  of { Z  -> True; S w5 -> True; };
                          S p27 -> case  v21  of { Z  -> True; S t2 -> True; };
                        };
                    };
                };
              Cons y18 w25 ->
                (((f
                      case  w30  of {
                        Stop  -> Stop;
                        State v4 p11 s18 ->
                          case  p30  of {
                            RM  -> case  v4  of { Z  -> Stop; S w3 -> (State ((add w3) p11) Z (S s18)); };
                            WH  ->
                              case  v4  of {
                                Z  -> case  s18  of { Z  -> Stop; S s4 -> (State ((add ((add Z) p11)) s4) (S Z) Z); };
                                S s19 ->
                                  case  s18  of {
                                    Z  -> (State ((add ((add (S s19)) p11)) Z) (S Z) Z);
                                    S v11 -> (State ((add ((add (S s19)) p11)) v11) (S Z) Z);
                                  };
                              };
                          };
                      })
                    y18)
                  w25);
            })))
    in
      (((f (State (S x) Z Z)) t8) u2));
}
