-- generated by hosc1 from examples/sc/synapse1.hs

data Action  = RM  | WH2 ;
data Number  = Z  | S Number;
data State  = State Number Number Number | Stop ;
data Boolean  = True  | False ;
data List a = Nil  | Cons a (List a);

(letrec
  g=(\z14->
    (\u14->
      case  u14  of {
        Nil  ->
          case  z14  of {
            State s6 s1 y13 ->
              case  s1  of {
                S x4 -> case  x4  of { S w8 -> False; Z  -> case  y13  of { S z5 -> False; Z  -> True; }; };
                Z  -> True;
              };
            Stop  -> True;
          };
        Cons z7 s4 ->
          ((g
              case  z7  of {
                RM  ->
                  case  z14  of {
                    State y5 r r10 ->
                      case  y5  of {
                        Z  -> Stop;
                        S t1 ->
                          (State
                            (letrec h=(\v14-> (\w14-> case  v14  of { Z  -> w14; S p9 -> (S ((h w14) p9)); }))
                            in
                              ((h t1) r))
                            Z
                            (S r10));
                      };
                    Stop  -> Stop;
                  };
                WH2  ->
                  case  z14  of {
                    State v1 r3 u13 ->
                      case  v1  of {
                        Z  ->
                          case  u13  of {
                            Z  -> Stop;
                            S v13 ->
                              (State
                                (letrec f1=(\p14-> (\r14-> case  r14  of { Z  -> p14; S y9 -> (S ((f1 y9) p14)); }))
                                in
                                  ((f1 v13) r3))
                                (S Z)
                                Z);
                          };
                        S y6 ->
                          case  u13  of {
                            Z  ->
                              (State
                                (S
                                  (letrec g1=(\s14-> (\t14-> case  s14  of { Z  -> t14; S u1 -> (S ((g1 t14) u1)); }))
                                  in
                                    ((g1 r3) y6)))
                                (S Z)
                                Z);
                            S s9 ->
                              (State
                                (S
                                  (letrec
                                    h1=(\x15->
                                      (\y15->
                                        (\z15->
                                          case  x15  of {
                                            Z  ->
                                              (letrec
                                                f2=(\u15->
                                                  (\v15->
                                                    case  u15  of { Z  -> v15; S w10 -> (S ((f2 v15) w10)); }))
                                              in
                                                ((f2 y15) z15));
                                            S p5 ->
                                              (S
                                                case  y15  of {
                                                  Z  ->
                                                    (letrec
                                                      g2=(\w15->
                                                        (\p15->
                                                          case  p15  of { Z  -> w15; S w12 -> (S ((g2 w12) w15)); }))
                                                    in
                                                      ((g2 p5) z15));
                                                  S w2 -> (S (((h1 p5) z15) w2));
                                                });
                                          })))
                                  in
                                    (((h1 s9) r3) y6)))
                                (S Z)
                                Z);
                          };
                      };
                    Stop  -> Stop;
                  };
              })
            s4);
      }))
in
  ((g a) b))
