-- generated by hosc1 from examples/sc/takenm.hs

data Number  = Z  | S Number;
data List a = Nil  | Cons a (List a);

(letrec
  f=(\u1->
    (\v1->
      case  v1  of { Nil  -> Nil; Cons y v -> case  u1  of { Z  -> Nil; S t -> (Cons y ((f t) v)); }; }))
in
  ((f n1) m1))
