-- generated by hosc1 from examples/sc/zip2.hs

data List a = Nil  | Cons a (List a);
data Pair a b = P a b;

(letrec
  f=(\w11->
    (\p11->
      case  w11  of {
        Nil  -> Nil;
        Cons u6 u9 -> case  p11  of { Nil  -> Nil; Cons t s2 -> (Cons (P (f1 u6) (f2 t)) ((f u9) s2)); };
      }))
in
  ((f l1) l2))
