-- generated by hosc0 from examples/mp/mp1a.hs

data Option a = Some a | None ;
data Nat  = Z  | S Nat;
data Bool  = True  | False ;

(letrec f=(\v3-> case  v3  of { Z  -> None; S w -> case  (f w)  of { None  -> None; Some w1 -> (Some (S w1)); }; })
in
  (f x))
