-- generated by hosc0 from examples/mp/mp1b.hs

data Option a = Some a | None ;
data Nat  = Z  | S Nat;

(letrec f=(\v3-> case  v3  of { Z  -> None; S t -> case  (f t)  of { Some t2 -> (Some (S t2)); }; }) in (f x))
