-- generated by hosc0 from debug/m2.hs

data Term a = Lit a | Oper (a->(a->a)) (Term a) (Term a);
data Val a = Val a;

case  t  of {
  Lit x4 -> (Lit x4);
  Oper u3 v7 s ->
    (letrec
      f=(\s7->
        (\t7->
          (\x8->
            case  s7  of {
              Lit v ->
                case  t7  of {
                  Lit y3 -> (Lit ((x8 v) y3));
                  Oper r2 w4 x5 -> case  (((f w4) x5) r2)  of { Lit u5 -> (Lit ((x8 v) u5)); };
                };
              Oper r1 u2 p7 ->
                case  (((f u2) p7) r1)  of {
                  Lit u4 ->
                    case  t7  of {
                      Lit r3 -> (Lit ((x8 u4) r3));
                      Oper v2 u7 z7 -> case  (((f u7) z7) v2)  of { Lit p4 -> (Lit ((x8 u4) p4)); };
                    };
                };
            })))
    in
      (((f v7) s) u3));
}
