-- generated by hosc0 from debug/tree.in.hs

data Tree a = Stub  | Leaf a | Node (Tree a) (Tree a);
data TreeNF a = StubNF  | NodeNF a (TreeNF a);
data Redex a = PRLeftStub (Tree a) | PRLeaf a | PRAssoc (Tree a) (Tree a) (Tree a);
data Contr a = Contr (Tree a) | Error ;
data Ctx a = CtE  | CtR a (Ctx a);
data Dec a = Val (Tree a) (TreeNF a) | Dec (Redex a) (Ctx a);
data Res a = Res (TreeNF a) | Bug ;

(letrec
  f=(\v7->
    (\w7->
      case  v7  of {
        Stub  ->
          (letrec
            g=(\p7->
              (\r7->
                (\s7->
                  case  p7  of { CtE  -> (Val r7 s7); CtR t2 v3 -> (((g v3) (Node (Leaf t2) r7)) (NodeNF t2 s7)); })))
          in
            (((g w7) Stub) StubNF));
        Leaf t4 -> (Dec (PRLeaf t4) w7);
        Node r y3 ->
          case  r  of {
            Stub  -> (Dec (PRLeftStub y3) w7);
            Leaf y4 -> ((f y3) (CtR y4 w7));
            Node r3 s3 -> (Dec (PRAssoc r3 s3 y3) w7);
          };
      }))
in
  ((f t) c1))
