-- generated by higher-level SC from examples/spec_hl/and_even_odd.in.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

(letrec f=(\z1-> case  z1  of { Z  -> False; S v -> case  v  of { Z  -> False; S u -> (f u); }; }) in (f n))
