-- generated by higher-level SC from examples/spec_hl/even_doubleAcc.in.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

case  x  of { Z  -> True; S u -> (letrec f=(\r2-> case  r2  of { Z  -> True; S x2 -> (f x2); }) in (f u)); }
