-- generated by higher-level SC from examples/spec_hl/even_plus_xx.in.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

case  x  of { Z  -> True; S r2 -> (letrec f=(\x3-> case  x3  of { Z  -> True; S y2 -> (f y2); }) in (f r2)); }
