-- generated by higher-level SC from examples/spec_hl/or_even_odd.in.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

(letrec f=(\w1-> case  w1  of { Z  -> True; S p -> case  p  of { Z  -> True; S x1 -> (f x1); }; }) in (f n))
