-- generated by hosc0 from examples/exp/even_doubleAcc_1.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

(letrec
  f=(\x3->
    (\y3->
      case  x3  of {
        S t -> ((f t) (S (S y3)));
        Z  ->
          (letrec g=(\z3-> case  z3  of { S s2 -> case  s2  of { Z  -> False; S x2 -> (g x2); }; Z  -> True; })
          in
            (g y3));
      }))
in
  ((f x) Z))
