-- generated by hosc0 from examples/exp/fo_dsl_3_a.hs

data Nat  = Z  | S Nat;
data Val  = Error  | N Nat | F (Val->Val);
data VarName  = VZ  | VS VarName;
data Exp  = NatZ  | NatS Exp | Var VarName | App Exp Exp | Lam VarName Exp | Fix VarName Exp;
data Env  = Empty  | Bind VarName Val Env;
data Bool  = True  | False ;

case  (F (\t20-> case  t20  of { Error  -> Error; N v19 -> Error; F r14 -> (r14 (F r14)); }))  of {
  Error  -> Error;
  F x6 -> (x6 (F x6));
  N v6 -> Error;
}
