-- generated by hosc0 from examples/exp/fo_dsl_1_b.hs

data Nat  = Z  | S Nat;
data Val  = Error  | N Nat | F (Val->Val);
data VarName  = VZ  | VS VarName;
data Exp  = NatZ  | NatS Exp | Var VarName | App Exp Exp | Lam VarName Exp | Fix VarName Exp;
data Env  = Empty  | Bind VarName Val Env;
data Bool  = True  | False ;

(letrec f=case  f  of { N u2 -> (N (S u2)); } in f)
