-- generated by hosc0 from examples/exp/fo_dsl_3_b.hs

data Nat  = Z  | S Nat;
data Val  = Error  | N Nat | F (Val->Val);
data VarName  = VZ  | VS VarName;
data Exp  = NatZ  | NatS Exp | Var VarName | App Exp Exp | Lam VarName Exp | Fix VarName Exp;
data Env  = Empty  | Bind VarName Val Env;
data Bool  = True  | False ;

case  (F (\t2-> case  t2  of { F z2 -> (z2 (F z2)); }))  of { F p1 -> (p1 (F p1)); }
