-- generated by hosc0 from examples/exp/fo_dsl_1_a.hs

data Nat  = Z  | S Nat;
data Val  = Error  | N Nat | F (Val->Val);
data VarName  = VZ  | VS VarName;
data Exp  = NatZ  | NatS Exp | Var VarName | App Exp Exp | Lam VarName Exp | Fix VarName Exp;
data Env  = Empty  | Bind VarName Val Env;
data Bool  = True  | False ;

(letrec f=case  f  of { Error  -> Error; F x6 -> Error; N w8 -> (N (S w8)); } in f)
