-- generated by hosc0 from exp/nondet1.hs

data Pair a b = P a b;
data Option a = Some a | None ;
data Enum  = A  | B ;

choice{(P choice{choice{B ; A;} ; A;} B) ; (P choice{choice{B ; A;} ; A;} B);}
