-- generated by hosc0 from examples/exp/or_even_odd_1.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

(letrec
  f=(\x2->
    case  x2  of {
      S w1 ->
        case  w1  of {
          Z  ->
            (letrec g=(\y2-> case  y2  of { Z  -> False; S y -> case  y  of { Z  -> True; S r -> (g r); }; })
            in
              (g v29));
          S u1 -> (f u1);
        };
      Z  -> True;
    })
in
  (f v29))
