-- generated by hosc0 from examples/exp/rev.hs

data List a = Nil  | Cons a (List a);

(letrec
  f=(\y3->
    case  y3  of {
      Nil  -> Nil;
      Cons r1 p1 ->
        (letrec g=(\z3-> case  z3  of { Cons s1 p2 -> (Cons s1 (g p2)); Nil  -> (Cons r1 Nil); }) in (g (f p1)));
    })
in
  (f xs))
