-- generated by higher-level SC from hl/even_doubleAcc.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

case  x  of { Z  -> True; S u1 -> (letrec f=(\r2-> case  r2  of { Z  -> True; S r -> (f r); }) in (f u1)); }
