-- generated by hosc0 from debug/d1.hs

data Bool  = True  | False ;
data Term a = Cst a | Opr (a->(a->a)) (Term a) (Term a);
data Ctx a = CtxHole  | CtxLeft (a->(a->a)) (Ctx a) (Term a) | CtxRight (a->(a->a)) a (Ctx a);
data PotRed a = PotRed (a->(a->a)) a a;
data ValDec a = Val a | Dec (PotRed a) (Ctx a);

(letrec
  f=(\r17->
    (\s17->
      case  r17  of {
        Cst s ->
          (letrec
            g=(\t17->
              (\x18->
                case  t17  of {
                  CtxHole  -> x18;
                  CtxLeft x17 u5 y5 -> ((f y5) (CtxRight x17 x18 u5));
                  CtxRight z2 t3 s10 -> ((g s10) ((z2 t3) x18));
                }))
          in
            ((g s17) s));
        Opr w2 z4 p1 -> ((f z4) (CtxLeft w2 s17 p1));
      }))
in
  ((f t) CtxHole))
