-- generated by hosc0 from debug/explode3.hs

data Nat  = Z  | S Nat;
data List a = Nil  | Cons a (List a);

(Cons
  (letrec f=(\u288-> case  u288  of { Z  -> (S (S (S (S (S (S (S Z))))))); S u267 -> (S (S (S (S (f u267))))); })
  in
    (f x))
  (Cons
    (letrec g=(\v288-> case  v288  of { Z  -> (S (S (S (S (S (S (S (S Z)))))))); S w264 -> (S (S (S (S (g w264))))); })
    in
      (g x))
    (Cons
      (letrec
        h=(\w288->
          case  w288  of { Z  -> (S (S (S (S (S (S (S (S (S Z))))))))); S x4 -> (S (S (S (S (h x4))))); })
      in
        (h x))
      (Cons
        (letrec
          g1=(\p288->
            case  p288  of { Z  -> (S (S (S (S (S (S (S (S (S (S Z)))))))))); S x19 -> (S (S (S (S (g1 x19))))); })
        in
          (g1 x))
        Nil))))
