-- generated by hosc0 from debug/explode4.hs

data Nat  = Z  | S Nat;
data List a = Nil  | Cons a (List a);

(Cons
  (letrec
    f=(\t1604->
      case  t1604  of {
        Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z)))))))))))))));
        S z1042 -> (S (S (S (S (S (S (S (S (f z1042)))))))));
      })
  in
    (f x))
  (Cons
    (letrec
      g=(\x1605->
        case  x1605  of {
          Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z))))))))))))))));
          S z743 -> (S (S (S (S (S (S (S (S (g z743)))))))));
        })
    in
      (g x))
    (Cons
      (letrec
        h=(\y1605->
          case  y1605  of {
            Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z)))))))))))))))));
            S s720 -> (S (S (S (S (S (S (S (S (h s720)))))))));
          })
      in
        (h x))
      (Cons
        (letrec
          g1=(\z1605->
            case  z1605  of {
              Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z))))))))))))))))));
              S s912 -> (S (S (S (S (S (S (S (S (g1 s912)))))))));
            })
        in
          (g1 x))
        (Cons
          (letrec
            h1=(\u1605->
              case  u1605  of {
                Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z)))))))))))))))))));
                S x717 -> (S (S (S (S (S (S (S (S (h1 x717)))))))));
              })
          in
            (h1 x))
          (Cons
            (letrec
              f2=(\v1605->
                case  v1605  of {
                  Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z))))))))))))))))))));
                  S v1403 -> (S (S (S (S (S (S (S (S (f2 v1403)))))))));
                })
            in
              (f2 x))
            (Cons
              (letrec
                g2=(\w1605->
                  case  w1605  of {
                    Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z)))))))))))))))))))));
                    S r894 -> (S (S (S (S (S (S (S (S (g2 r894)))))))));
                  })
              in
                (g2 x))
              (Cons
                (letrec
                  h2=(\p1605->
                    case  p1605  of {
                      Z  -> (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S Z))))))))))))))))))))));
                      S w110 -> (S (S (S (S (S (S (S (S (h2 w110)))))))));
                    })
                in
                  (h2 x))
                Nil))))))))
