-- generated by hosc0 from debug/in.hs

data Term a = Cst a | Opr (a->(a->a)) (Term a) (Term a);
data Ctx a = Empty  | Left (a->(a->a)) (Ctx a) (Term a) | Right (a->(a->a)) a (Ctx a);

(letrec f=(\s2-> case  s2  of { Cst y2 -> y2; Opr x2 z u2 -> ((x2 (f z)) (f u2)); }) in (f t))
