-- generated by hosc0 from debug/d1.hs

data Bool  = True  | False ;
data Term a = Cst a | Opr (a->(a->a)) (Term a) (Term a);
data Ctx a = CtxHole  | CtxLeft (a->(a->a)) (Ctx a) (Term a) | CtxRight (a->(a->a)) a (Ctx a);
data PotRed a = PotRed (a->(a->a)) a a;
data ValDec a = Val a | Dec (PotRed a) (Ctx a);

(letrec
  f=(\r17->
    (\s17->
      case  r17  of {
        Cst z6 ->
          (letrec
            g=(\t17->
              (\x18->
                case  t17  of {
                  CtxHole  -> x18;
                  CtxLeft u14 w14 t14 -> ((f t14) (CtxRight u14 x18 w14));
                  CtxRight p11 z11 x10 -> ((g x10) ((p11 z11) x18));
                }))
          in
            ((g s17) z6));
        Opr p1 u t2 -> ((f u) (CtxLeft p1 s17 t2));
      }))
in
  ((f t) CtxHole))
