package hosc.exp

import scala.util.parsing.input.StreamReader
import scala.util.parsing.input.CharArrayReader

import java.io.File
import java.io.FileInputStream
import java.io.InputStreamReader
import java.io.FileReader
import java.io.FileWriter
import java.io.BufferedReader

import hosc.CodeConstructor
import hosc.ProcessTreeSVG
import hosc.HLanguage._
import hosc.Util._

object SuperCompilerApp1 {
  val help = """usage: hosc.SuperCompilerApp1 -si sinput_file -t tree_output_file -p program_output_file
  |Where:
  |sinput_file           path to input file (code in hl language)
  |tree_output_file      path to file where process tree will be placed (in SVG format)
  |program_output_file   path to file where residual program will be placed (in hl language)
  |""".stripMargin
  def main(args : Array[String]) : Unit = {
    var fileName: String = null
    var outFileName: String = null
    var outProgramFileName: String = null
    var sugared = false
    args.toList match {
      case "-si" :: input_file :: "-t" :: output_file :: "-p" :: output_file_1 :: Nil =>
        fileName = input_file
        outFileName = output_file
        outProgramFileName = output_file_1
        sugared = true
      case "-help" :: Nil => 
        println(help)
        return
      case _ => 
        throw new IllegalArgumentException("run hosc.SuperCompilerApp1 -help for help")       
    }
    
    val program = programFromFile(fileName)
    val sc = new SuperCompiler1(program)
    val pt = sc.buildProcessTree(program.goal)    
    val svg = new ProcessTreeSVG(pt).treeToSVG
    
    val svgFile = new java.io.File(outFileName)
    if (!svgFile.exists){
      svgFile.getParentFile.mkdirs()
      svgFile.createNewFile()
    } 
    scala.xml.XML.save(outFileName, svg)
    
    val g = new CodeConstructor(program, pt, true)
    val p = g.generateProgram()
    val doc = p.toDoc
    val slFile = new java.io.File(outProgramFileName)
    if (!slFile.exists){
      slFile.createNewFile()
    }
    val fw = new FileWriter(slFile);
    fw.write("-- generated by hosc1 from " + fileName + "\n")
    doc.format(120, fw)
    fw.flush();
    fw.close();
  }
}
