-- generated by hosc0 from examples/sc/01_loop.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec f=(\r2-> (\s2-> case  r2  of { Z  -> (d s2); S r1 -> ((f r1) (S s2)); })) in ((f x) y))
