-- generated by hosc0 from examples/sc/church.hs

data Nat  = Z  | S Nat;

(\r2->
  (\r->
    (letrec
      f=(\r6->
        case  r6  of {
          Z  -> (letrec g=(\s6-> case  s6  of { Z  -> r; S v3 -> (r2 (g v3)); }) in (g y));
          S p6 -> (r2 (f p6));
        })
    in
      (f x))))
