-- generated by hosc0 from examples/sc/eqnum.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;
data Pair  = P Number Number;

(letrec
  f=(\x21->
    (\y21->
      case  x21  of {
        S u12 ->
          case  y21  of {
            Z  ->
              (letrec
                g=(\z21->
                  (\u21->
                    case  z21  of {
                      Z  ->
                        (letrec
                          h=(\v21->
                            (\w21->
                              case  v21  of {
                                Z  -> False;
                                S y1 ->
                                  case  w21  of {
                                    Z  -> case  y1  of { Z  -> True; S v13 -> False; };
                                    S v -> ((h y1) v);
                                  };
                              }))
                        in
                          ((h u21) y));
                      S x15 -> case  u21  of { Z  -> False; S r11 -> ((g x15) r11); };
                    }))
              in
                ((g u12) x));
            S s12 -> ((f u12) s12);
          };
        Z  ->
          (letrec
            f1=(\p21->
              (\r21->
                case  p21  of {
                  Z  ->
                    (letrec
                      g1=(\s21->
                        (\t21->
                          case  s21  of {
                            Z  -> case  t21  of { Z  -> True; S p11 -> False; };
                            S t4 -> case  t21  of { Z  -> False; S r13 -> ((g1 t4) r13); };
                          }))
                    in
                      ((g1 r21) x));
                  S z19 ->
                    case  r21  of { Z  -> case  z19  of { Z  -> False; S y7 -> False; }; S r6 -> ((f1 z19) r6); };
                }))
          in
            ((f1 y21) y));
      }))
in
  ((f x) y))
