-- generated by hosc0 from examples/sc/eqnumxx.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;
data Pair  = P Number Number;

(letrec f=(\r2-> case  r2  of { Z  -> True; S x1 -> (f x1); }) in (f x))
