-- generated by hosc0 from examples/sc/even2.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec
  h=(\r2->
    (\s2->
      case  r2  of {
        S v2 -> ((h v2) (S (S s2)));
        Z  ->
          (letrec f1=(\t2-> case  t2  of { Z  -> True; S u2 -> case  u2  of { Z  -> False; S r -> (f1 r); }; })
          in
            (f1 s2));
      }))
in
  ((h t) Z))
