-- generated by hosc0 from examples/sc/even.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec
  f=(\p3->
    (\r3->
      case  p3  of {
        S v3 -> ((f v3) (S (S r3)));
        Z  ->
          (letrec g=(\s3-> case  s3  of { S z3 -> case  z3  of { S t -> (g t); Z  -> False; }; Z  -> True; })
          in
            (g r3));
      }))
in
  ((f n) Z))
