-- generated by hosc0 from examples/sc/evenSS.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec
  f=(\z4->
    (\u4->
      case  z4  of {
        S z -> ((f z) (S (S u4)));
        Z  ->
          (letrec g=(\v4-> case  v4  of { Z  -> True; S s -> case  s  of { Z  -> False; S u2 -> (g u2); }; })
          in
            (g u4));
      }))
in
  ((f n) Z))
