-- generated by hosc0 from examples/sc/exp.hs

data Number  = Z  | S Number;
data Boolean  = True  | False ;

(letrec g=(\v2-> (\w2-> case  v2  of { S y1 -> ((g y1) (S w2)); Z  -> (d (S w2)); })) in ((g x) Z))
