-- generated by hosc0 from examples/sc/fib.hs

data Nat  = Z  | S Nat;

(letrec
  f=(\t2->
    case  t2  of {
      Z  -> (S Z);
      S s1 -> (letrec g=(\x3-> case  x3  of { Z  -> (S Z); S u -> ((add (g u)) (f u)); }) in (g s1));
    })
in
  (f n))
