-- generated by hosc0 from examples/sc/filter.hs

data List a = Nil  | Cons a (List a);
data Boolean  = True  | False ;

(letrec
  g=(\s7->
    case  s7  of { Nil  -> Nil; Cons u r7 -> case  (p (f u))  of { True  -> (Cons (f u) (g r7)); False  -> (g r7); }; })
in
  (g xs))
