-- generated by hosc0 from examples/sc/leq_add.hs

data N  = Z  | S N;
data B  = True  | False ;

(letrec
  f=(\v4->
    (\w4->
      case  v4  of {
        S s2 ->
          case  w4  of {
            Z  ->
              (letrec
                g=(\p4->
                  (\r4->
                    case  p4  of { S v2 -> case  r4  of { Z  -> True; S r -> ((g v2) r); }; Z  -> False; }))
              in
                ((g x) s2));
            S x3 -> ((f s2) x3);
          };
        Z  -> True;
      }))
in
  ((f x) y))
