-- generated by hosc0 from examples/sc/letrec.hs

data List a = Nil  | Cons a (List a);

(letrec
  g=(\t4->
    case  t4  of {
      Nil  -> (letrec h=(\x5-> case  x5  of { Nil  -> z; Cons u3 y4 -> (Cons u3 (h y4)); }) in (h y));
      Cons x2 r3 -> (Cons x2 (g r3));
    })
in
  (g x))
