-- generated by hosc0 from examples/sc/letrec_rev.hs

data List a = Nil  | Cons a (List a);

(letrec
  g=(\y3->
    case  y3  of {
      Nil  -> Nil;
      Cons v1 y2 ->
        (letrec h=(\z3-> case  z3  of { Cons u s1 -> (Cons u (h s1)); Nil  -> (Cons v1 Nil); }) in (h (g y2)));
    })
in
  (g zs))
