-- generated by hosc0 from examples/mc/ltl5.hs

data List a = Cons a (List a);
data Bool  = True  | False ;

((p
    (\y->
      (letrec
        f=(\r10->
          (\s10->
            case  r10  of { True  -> case  s10  of { Cons w6 w4 -> ((p (\y2-> ((f y2) w4))) w4); }; False  -> True; }))
      in
        ((f y) states))))
  states)
