-- generated by hosc0 from examples/sc/min.hs

data List a = Nil  | Cons a (List a);
data B  = True  | False ;
data N  = Z  | S N;

case 
(letrec
  f=(\x13->
    case  x13  of {
      Nil  -> Nil;
      Cons p s5 ->
        (letrec
          g=(\y13->
            case  y13  of {
              Cons y s8 -> case  ((lessOrEq p) y)  of { False  -> (Cons y (g s8)); True  -> (Cons p (Cons y s8)); };
              Nil  -> (Cons p Nil);
            })
        in
          (g (f s5)));
    })
in
  (f w43))
 of {
  Cons r6 r4 ->
    case  ((lessOrEq w42) r6)  of {
      False  -> case  ((lessOrEq x) r6)  of { False  -> r6; True  -> x; };
      True  -> case  ((lessOrEq x) w42)  of { False  -> w42; True  -> x; };
    };
  Nil  -> case  ((lessOrEq x) w42)  of { False  -> w42; True  -> x; };
}
