-- generated by hosc0 from examples/sc/rev.hs

data List a = Nil  | Cons a (List a);

(letrec
  f=(\y3->
    case  y3  of {
      Nil  -> Nil;
      Cons y1 w1 ->
        (letrec g=(\z3-> case  z3  of { Cons y2 u1 -> (Cons y2 (g u1)); Nil  -> (Cons y1 Nil); }) in (g (f w1)));
    })
in
  (f xs))
