-- generated by hosc0 from examples/sc/synapse1.hs

data Action  = RM  | WH2 ;
data Number  = Z  | S Number;
data State  = State Number Number Number | Stop ;
data Boolean  = True  | False ;
data List a = Nil  | Cons a (List a);

(letrec
  g=(\y50->
    (\z50->
      (\u50->
        (\v50->
          case  y50  of {
            Cons w1 x43 ->
              ((((g x43)
                    case  w1  of {
                      RM  ->
                        case  z50  of {
                          State w49 z29 r17 ->
                            case  w49  of {
                              S y16 ->
                                (State
                                  (letrec h4=(\y53-> (\z53-> case  y53  of { Z  -> z53; S z28 -> (S ((h4 z53) z28)); }))
                                  in
                                    ((h4 y16) z29))
                                  Z
                                  (S r17));
                              Z  -> Stop;
                            };
                          Stop  -> Stop;
                        };
                      WH2  ->
                        case  u50  of {
                          State w48 s38 y20 ->
                            case  w48  of {
                              S v6 ->
                                case  y20  of {
                                  S x24 ->
                                    (State
                                      (S
                                        (letrec
                                          f5=(\u53->
                                            (\v53->
                                              (\w53->
                                                case  u53  of {
                                                  Z  ->
                                                    (letrec
                                                      g5=(\p53->
                                                        (\r53->
                                                          case  p53  of { Z  -> r53; S t39 -> (S ((g5 r53) t39)); }))
                                                    in
                                                      ((g5 v53) w53));
                                                  S t28 ->
                                                    (S
                                                      case  v53  of {
                                                        Z  ->
                                                          (letrec
                                                            h5=(\s53->
                                                              (\t53->
                                                                case  s53  of {
                                                                  Z  -> t53;
                                                                  S y43 -> (S ((h5 t53) y43));
                                                                }))
                                                          in
                                                            ((h5 w53) t28));
                                                        S v15 -> (S (((f5 t28) w53) v15));
                                                      });
                                                })))
                                        in
                                          (((f5 x24) s38) v6)))
                                      (S Z)
                                      Z);
                                  Z  ->
                                    (State
                                      (S
                                        (letrec
                                          f6=(\x54->
                                            (\y54->
                                              case  x54  of { Z  -> y54; S w29 -> (S ((f6 y54) w29)); }))
                                        in
                                          ((f6 s38) v6)))
                                      (S Z)
                                      Z);
                                };
                              Z  ->
                                case  y20  of {
                                  S v48 ->
                                    (State
                                      (letrec
                                        g6=(\z54->
                                          (\u54->
                                            case  z54  of { Z  -> u54; S t8 -> (S ((g6 u54) t8)); }))
                                      in
                                        ((g6 s38) v48))
                                      (S Z)
                                      Z);
                                  Z  -> Stop;
                                };
                            };
                          Stop  -> Stop;
                        };
                    })
                  case  w1  of {
                    RM  ->
                      case  z50  of {
                        State w12 x z41 ->
                          case  w12  of {
                            S s16 ->
                              (State
                                (letrec h=(\w50-> (\p50-> case  w50  of { Z  -> p50; S s -> (S ((h p50) s)); }))
                                in
                                  ((h s16) x))
                                Z
                                (S z41));
                            Z  -> Stop;
                          };
                        Stop  -> Stop;
                      };
                    WH2  ->
                      case  u50  of {
                        State z6 v22 t36 ->
                          case  z6  of {
                            S v20 ->
                              case  t36  of {
                                S p43 ->
                                  (State
                                    (S
                                      (letrec
                                        f1=(\r50->
                                          (\s50->
                                            (\t50->
                                              case  r50  of {
                                                Z  ->
                                                  (letrec
                                                    g1=(\x51->
                                                      (\y51->
                                                        case  x51  of { Z  -> y51; S t37 -> (S ((g1 y51) t37)); }))
                                                  in
                                                    ((g1 s50) t50));
                                                S y44 ->
                                                  (S
                                                    case  s50  of {
                                                      Z  ->
                                                        (letrec
                                                          h1=(\z51->
                                                            (\u51->
                                                              case  z51  of {
                                                                Z  -> u51;
                                                                S t40 -> (S ((h1 u51) t40));
                                                              }))
                                                        in
                                                          ((h1 t50) y44));
                                                      S z33 -> (S (((f1 y44) t50) z33));
                                                    });
                                              })))
                                      in
                                        (((f1 p43) v22) v20)))
                                    (S Z)
                                    Z);
                                Z  ->
                                  (State
                                    (S
                                      (letrec
                                        f2=(\v51->
                                          (\w51->
                                            case  v51  of { Z  -> w51; S r13 -> (S ((f2 w51) r13)); }))
                                      in
                                        ((f2 v22) v20)))
                                    (S Z)
                                    Z);
                              };
                            Z  ->
                              case  t36  of {
                                S t44 ->
                                  (State
                                    (letrec
                                      g2=(\p51->
                                        (\r51->
                                          case  p51  of { Z  -> r51; S v33 -> (S ((g2 r51) v33)); }))
                                    in
                                      ((g2 v22) t44))
                                    (S Z)
                                    Z);
                                Z  -> Stop;
                              };
                          };
                        Stop  -> Stop;
                      };
                  })
                case  w1  of {
                  RM  ->
                    case  z50  of {
                      State v34 r46 x33 ->
                        case  v34  of {
                          S p26 ->
                            (State
                              (letrec h2=(\s51-> (\t51-> case  s51  of { Z  -> t51; S s39 -> (S ((h2 t51) s39)); }))
                              in
                                ((h2 p26) r46))
                              Z
                              (S x33));
                          Z  -> Stop;
                        };
                      Stop  -> Stop;
                    };
                  WH2  ->
                    case  u50  of {
                      State r32 y17 r1 ->
                        case  r32  of {
                          S p32 ->
                            case  r1  of {
                              S t30 ->
                                (State
                                  (S
                                    (letrec
                                      f3=(\x52->
                                        (\y52->
                                          (\z52->
                                            case  x52  of {
                                              Z  ->
                                                (letrec
                                                  g3=(\u52->
                                                    (\v52->
                                                      case  u52  of { Z  -> v52; S r41 -> (S ((g3 v52) r41)); }))
                                                in
                                                  ((g3 y52) z52));
                                              S s30 ->
                                                (S
                                                  case  y52  of {
                                                    Z  ->
                                                      (letrec
                                                        h3=(\w52->
                                                          (\p52->
                                                            case  w52  of { Z  -> p52; S p36 -> (S ((h3 p52) p36)); }))
                                                      in
                                                        ((h3 z52) s30));
                                                    S v39 -> (S (((f3 s30) z52) v39));
                                                  });
                                            })))
                                    in
                                      (((f3 t30) y17) p32)))
                                  (S Z)
                                  Z);
                              Z  ->
                                (State
                                  (S
                                    (letrec
                                      f4=(\r52->
                                        (\s52->
                                          case  r52  of { Z  -> s52; S x39 -> (S ((f4 s52) x39)); }))
                                    in
                                      ((f4 y17) p32)))
                                  (S Z)
                                  Z);
                            };
                          Z  ->
                            case  r1  of {
                              S r14 ->
                                (State
                                  (letrec g4=(\t52-> (\x53-> case  t52  of { Z  -> x53; S x20 -> (S ((g4 x53) x20)); }))
                                  in
                                    ((g4 y17) r14))
                                  (S Z)
                                  Z);
                              Z  -> Stop;
                            };
                        };
                      Stop  -> Stop;
                    };
                });
            Nil  ->
              case  v50  of {
                State t33 u15 t2 ->
                  case  u15  of {
                    S t25 -> case  t25  of { S p10 -> False; Z  -> case  t2  of { S s28 -> False; Z  -> True; }; };
                    Z  -> True;
                  };
                Stop  -> True;
              };
          }))))
in
  ((((g b) a) a) a))
