-- generated by hosc0 from examples/sc/synapse2.hs

data Action  = RM  | WH2 ;
data Number  = Z  | S Number;
data State  = State Number Number Number | Stop ;
data Boolean  = True  | False ;
data List a = Nil  | Cons a (List a);

(letrec
  g=(\u50->
    (\v50->
      (\w50->
        (\p50->
          case  u50  of {
            Cons v39 t38 ->
              ((((g t38)
                    case  v39  of {
                      RM  ->
                        case  v50  of {
                          State t20 u36 u41 ->
                            case  t20  of {
                              S s22 ->
                                (State
                                  (letrec h4=(\u53-> (\v53-> case  u53  of { Z  -> v53; S p43 -> (S ((h4 v53) p43)); }))
                                  in
                                    ((h4 s22) u36))
                                  Z
                                  (S u41));
                              Z  -> Stop;
                            };
                          Stop  -> Stop;
                        };
                      WH2  ->
                        case  w50  of {
                          State x25 p18 p44 ->
                            case  x25  of {
                              S v8 ->
                                case  p44  of {
                                  S y38 ->
                                    (State
                                      (S
                                        (letrec
                                          f5=(\w53->
                                            (\p53->
                                              (\r53->
                                                case  w53  of {
                                                  Z  ->
                                                    (letrec
                                                      g5=(\s53->
                                                        (\t53->
                                                          case  s53  of { Z  -> t53; S s35 -> (S ((g5 t53) s35)); }))
                                                    in
                                                      ((g5 p53) r53));
                                                  S p32 ->
                                                    (S
                                                      case  p53  of {
                                                        Z  ->
                                                          (letrec
                                                            h5=(\x54->
                                                              (\y54->
                                                                case  x54  of {
                                                                  Z  -> y54;
                                                                  S s11 -> (S ((h5 y54) s11));
                                                                }))
                                                          in
                                                            ((h5 r53) p32));
                                                        S v37 -> (S (((f5 p32) r53) v37));
                                                      });
                                                })))
                                        in
                                          (((f5 y38) p18) v8)))
                                      (S Z)
                                      Z);
                                  Z  ->
                                    (State
                                      (S
                                        (letrec
                                          f6=(\z54->
                                            (\u54->
                                              case  z54  of { Z  -> u54; S t3 -> (S ((f6 u54) t3)); }))
                                        in
                                          ((f6 p18) v8)))
                                      (S Z)
                                      Z);
                                };
                              Z  ->
                                case  p44  of {
                                  S s37 ->
                                    (State
                                      (letrec
                                        g6=(\v54->
                                          (\w54->
                                            case  v54  of { Z  -> w54; S y48 -> (S ((g6 w54) y48)); }))
                                      in
                                        ((g6 p18) s37))
                                      (S Z)
                                      Z);
                                  Z  -> Stop;
                                };
                            };
                          Stop  -> Stop;
                        };
                    })
                  case  v39  of {
                    RM  ->
                      case  v50  of {
                        State p31 x22 x48 ->
                          case  p31  of {
                            S r19 ->
                              (State
                                (letrec h2=(\x52-> (\y52-> case  x52  of { Z  -> y52; S u46 -> (S ((h2 y52) u46)); }))
                                in
                                  ((h2 r19) x22))
                                Z
                                (S x48));
                            Z  -> Stop;
                          };
                        Stop  -> Stop;
                      };
                    WH2  ->
                      case  w50  of {
                        State y29 t39 p ->
                          case  y29  of {
                            S u43 ->
                              case  p  of {
                                S y43 ->
                                  (State
                                    (S
                                      (letrec
                                        f3=(\z52->
                                          (\u52->
                                            (\v52->
                                              case  z52  of {
                                                Z  ->
                                                  (letrec
                                                    g3=(\w52->
                                                      (\p52->
                                                        case  w52  of { Z  -> p52; S s25 -> (S ((g3 p52) s25)); }))
                                                  in
                                                    ((g3 u52) v52));
                                                S x32 ->
                                                  (S
                                                    case  u52  of {
                                                      Z  ->
                                                        (letrec
                                                          h3=(\r52->
                                                            (\s52->
                                                              case  r52  of {
                                                                Z  -> s52;
                                                                S z31 -> (S ((h3 s52) z31));
                                                              }))
                                                        in
                                                          ((h3 v52) x32));
                                                      S z5 -> (S (((f3 x32) v52) z5));
                                                    });
                                              })))
                                      in
                                        (((f3 y43) t39) u43)))
                                    (S Z)
                                    Z);
                                Z  ->
                                  (State
                                    (S
                                      (letrec
                                        f4=(\t52->
                                          (\x53->
                                            case  t52  of { Z  -> x53; S u44 -> (S ((f4 x53) u44)); }))
                                      in
                                        ((f4 t39) u43)))
                                    (S Z)
                                    Z);
                              };
                            Z  ->
                              case  p  of {
                                S t15 ->
                                  (State
                                    (letrec g4=(\y53-> (\z53-> case  y53  of { Z  -> z53; S s1 -> (S ((g4 z53) s1)); }))
                                    in
                                      ((g4 t39) t15))
                                    (S Z)
                                    Z);
                                Z  -> Stop;
                              };
                          };
                        Stop  -> Stop;
                      };
                  })
                case  v39  of {
                  RM  ->
                    case  v50  of {
                      State s49 v26 p13 ->
                        case  s49  of {
                          S v45 ->
                            (State
                              (letrec h=(\r50-> (\s50-> case  r50  of { Z  -> s50; S v38 -> (S ((h s50) v38)); }))
                              in
                                ((h v45) v26))
                              Z
                              (S p13));
                          Z  -> Stop;
                        };
                      Stop  -> Stop;
                    };
                  WH2  ->
                    case  w50  of {
                      State u21 u31 x49 ->
                        case  u21  of {
                          S r6 ->
                            case  x49  of {
                              S r12 ->
                                (State
                                  (S
                                    (letrec
                                      f1=(\t50->
                                        (\x51->
                                          (\y51->
                                            case  t50  of {
                                              Z  ->
                                                (letrec
                                                  g1=(\z51->
                                                    (\u51->
                                                      case  z51  of { Z  -> u51; S r31 -> (S ((g1 u51) r31)); }))
                                                in
                                                  ((g1 x51) y51));
                                              S s32 ->
                                                (S
                                                  case  x51  of {
                                                    Z  ->
                                                      (letrec
                                                        h1=(\v51->
                                                          (\w51->
                                                            case  v51  of { Z  -> w51; S z33 -> (S ((h1 w51) z33)); }))
                                                      in
                                                        ((h1 y51) s32));
                                                    S u -> (S (((f1 s32) y51) u));
                                                  });
                                            })))
                                    in
                                      (((f1 r12) u31) r6)))
                                  (S Z)
                                  Z);
                              Z  ->
                                (State
                                  (S
                                    (letrec
                                      f2=(\p51->
                                        (\r51->
                                          case  p51  of { Z  -> r51; S p22 -> (S ((f2 r51) p22)); }))
                                    in
                                      ((f2 u31) r6)))
                                  (S Z)
                                  Z);
                            };
                          Z  ->
                            case  x49  of {
                              S s20 ->
                                (State
                                  (letrec g2=(\s51-> (\t51-> case  s51  of { Z  -> t51; S p1 -> (S ((g2 t51) p1)); }))
                                  in
                                    ((g2 u31) s20))
                                  (S Z)
                                  Z);
                              Z  -> Stop;
                            };
                        };
                      Stop  -> Stop;
                    };
                });
            Nil  ->
              case  p50  of {
                State z42 r17 z44 ->
                  case  r17  of {
                    S v1 -> case  v1  of { S w43 -> False; Z  -> case  z44  of { S p20 -> False; Z  -> True; }; };
                    Z  -> True;
                  };
                Stop  -> True;
              };
          }))))
in
  ((((g y) (State (S x) Z Z)) (State (S x) Z Z)) (State (S x) Z Z)))
