-- generated by hosc0 from examples/sc/takenm.hs

data Number  = Z  | S Number;
data List a = Nil  | Cons a (List a);

(letrec
  f=(\w2->
    (\p2->
      case  w2  of { Nil  -> Nil; Cons z s -> case  p2  of { Z  -> Nil; S t1 -> (Cons z ((f s) t1)); }; }))
in
  ((f m1) n1))
