-- generated by higher-level SC from hl/and_even_odd.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

(letrec f=(\z1-> case  z1  of { Z  -> False; S x1 -> case  x1  of { Z  -> False; S w -> (f w); }; }) in (f n))
