-- generated by higher-level SC from hl/even_plus_xx.hs

data Bool  = True  | False ;
data Nat  = Z  | S Nat;

case  x  of { Z  -> True; S v1 -> (letrec f=(\x3-> case  x3  of { Z  -> True; S r1 -> (f r1); }) in (f v1)); }
